version: 3

services:
  bun:
    container_name: vitepress
    image: oven/bun:slim
    user: root
    environment:
      - TZ=Asia/Shanghai
    working_dir: /home/bun/app
    volumes:
      - .:/home/bun/app
    ports:
      - 5173:5173
    command: bun run docs:dev
networks:
  default:
    external:
      name: podman
